networks:
  events-network-test:

services:
  api:
    image: events-api
    container_name: events-api-api-1
    # image: node:20
    build:
      context: ./events-api/.
      dockerfile: Dockerfile
    networks:
      - events-network-test
    ports:
      - "3002:3002"
    depends_on:
      - db
    # command: ["cat", "package.json"]
  web:
    image: events-app
    container_name: events-api-web-1
    # image: node:20
    build:
      context: ./events-app/.
      dockerfile: Dockerfile
    networks:
      - events-network-test
    ports:
      - "3000:3000"
    depends_on:
      - api
    # command: ["npm", "run", "start"]
  db:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
